In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('Censo2020/Viviendas19.CSV')
df

,ENT,MUN,LOC50K,ID_VIV,COBERTURA,ESTRATO,UPM,FACTOR,CLAVIVP,PAREDES,...,ALIM_ADL1,ALIM_ADL2,ING_ALIM_ADL1,ING_ALIM_ADL2,ING_ALIM_ADL3,TIPOHOG,INGTRHOG,JEFE_SEXO,JEFE_EDAD,TAMLOC
0,19,1,0,190010000001,1,19-001-0000-03,1,1,2,8.0,...,2,4,2,4,6,1,12900.0,3,30,1
1,19,1,0,190010000002,1,19-001-0000-03,1,1,2,8.0,...,2,4,2,4,6,1,20640.0,1,31,1
2,19,1,0,190010000003,1,19-001-0000-03,1,1,2,8.0,...,2,4,2,4,6,1,20640.0,1,31,1
3,19,1,0,190010000004,1,19-001-0000-03,1,1,2,8.0,...,2,4,2,4,6,1,16770.0,1,57,1
4,19,1,0,190010000005,1,19-001-0000-03,1,1,1,8.0,...,2,4,2,4,6,1,51600.0,1,47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98310,19,51,0,190510000880,2,19-051-0000-03,15,1,2,8.0,...,2,4,2,4,6,5,7310.0,1,50,1
98311,19,51,0,190510000881,2,19-051-0000-03,16,2,1,8.0,...,2,4,2,4,6,5,0.0,1,75,1
98312,19,51,0,190510000882,2,19-051-0000-03,17,2,1,8.0,...,1,3,1,4,6,1,6620.0,1,75,1
98313,19,51,0,190510000883,2,19-051-0000-03,18,1,1,8.0,...,2,4,2,4,6,2,10000.0,1,54,1
98314,19,51,0,190510000884,2,19-051-0000-03,19,2,1,8.0,...,2,4,2,4,6,1,3800.0,1,69,1

In [9]:
prueba = df.groupby('MUN')['CLAVIVP'].value_counts()

In [10]:
convertir = {
    '1': 'Casa Ãºnica en el terreno',
    '2': 'Casa que comparte terreno con otra(s)',
    '3': 'Casa dÃºplex',
    '4': 'Departamento en edificio',
    '5': 'Vivienda en vecindad o cuarterÃ­a',
    '6': 'Vivienda en cuarto de azotea de un edificio',
    '7': 'Local no construido para habitaciÃ³n',
    '8': 'Vivienda mÃ³vil',
    '9': 'Refugio',
    '99': 'No especificado de vivienda particular'
}

In [28]:
num = prueba[21].sum()
num

4326

In [63]:
estadistica = (prueba / prueba.sum()) *100

In [64]:
estadistica

MUN  CLAVIVP
1    1          0.660123
     2          0.141382
     7          0.003051
2    1          1.112750
     2          0.158674
                  ...
50   2          0.075268
     7          0.002034
51   1          0.735391
     2          0.162742
     7          0.001017
Name: CLAVIVP, Length: 238, dtype: float64